### ISSUE TITLE
Missing fcsgain.txt file

### ISSUE THREAD

**Issue by privdonut123** [xilinliang/FCS-ECal-pi0-reconstruction#1]
fcsgain.txt file is missing from working directory. This messes with the perl script in /submitScheduler. This disappeared from the the last repository you had. Can copy from /star/u/bmagh001/FCS-ECal-pi0-reconstruction/fcsgain.txt

**Comment by xilinliang** [comment]
Thanks for pointing out the error. fcsgain.txt file is no longer needed with the new algorithm. The gain file will be read from STAR database. I correct the xml file correspondingly.

**Comment by xilinliang** [comment]
Thanks for pointing out the error. fcsgain.txt file is no longer needed with the new algorithm. The gain file will be read from STAR database. I correct the xml file correspondingly.
